### ISSUE TITLE
Clean up translations in discopower

### ISSUE THREAD

**Issue by ghalse** [simplesamlphp/simplesamlphp-module-discopower#3]
We need to remove the call to `includeInlineTranslation` to fix [simplesamlphp/simplsamlphp#463](https://github.com/simplesamlphp/simplesamlphp/issues/463). See [simplesamlphp/simplsamlphp#1187](https://github.com/simplesamlphp/simplesamlphp/issue/1187).

**Comment by ghalse** [comment]
I think @dnmvisser's change at [simplesamlphp/simplesamlphp#1081](https://github.com/simplesamlphp/simplesamlphp/pull/1081) makes the use of getTag() unavoidable since there's no longer any way to know whether a namespaced tag should exist or not.

The includeInlineTranslation() can be removed by assuming that tabs that don't already exist in a namespaced version should be translated as literal strings:
```php
if ($translator->getTag('{discopower:tabs:'.$tab.'}') === null) {
    $t->data['tabNames'][$tab] = $translator::noop($tab);
} else {
    $t->data['tabNames'][$tab] = $translator::noop('{discopower:tabs:'.$tab.'}');
}
```
which is probably in line with the general move in that direction. This neatly fixes the Twig version. The legacy version requires some more work to determine when a tag should be passed through `t()` so as to avoid the 'not translated()' wrapper. That's also probably okay since the legacy templates have a defined life.

However, I cannot think of a way to remove the call to getTag() without reintroducing the hard-coded array of legacy tag names. [simplesamlphp/simplesamlphp#462](https://github.com/simplesamlphp/simplesamlphp/issues/462) suggests this is a problem.

I guess my question now is which is the greater evil?

**Comment by tvdijen** [comment]
I think we do the same here for dynamically translating entityID's to more human-friendly names:
https://github.com/simplesamlphp/simplesamlphp-module-statistics/blob/master/lib/Statistics/FieldPresentation/Entity.php#L17

We would have to change the configuration-format so that translations for tab-names can be set.

**Comment by thijskh** [comment]
The concept of the fix by @ghalse is fine I think (check if old tag exists, if not, noop). We do not need to worry about legacy templating systems because those have already been removed in master.

The suggested fix does not work for me however, because getTag() always returns null because getTag() only searches legacy dictionaries. I've now changed it to the following and that works just like expected for me:
```php
            $translatableTag = "{discopower:tabs:$tab}";
            if ($translator::translateSingularGettext($translatableTag) === $translatableTag) {
                $t->data['tabNames'][$tab] = $translator::noop($tab);
            } else {
                $t->data['tabNames'][$tab] = $translator::noop($translatableTag);
            }
```

OK if I apply this to master?

**Comment by ghalse** [comment]
Life gets simpler when we get rid of the legacy stuff :)
